module.exports = {
  en: {
    label: 'GC Design System Map Extension',
    home: 'GC Design System Map Extension',
    contact: 'Contact',
    contactus: 'Contact us',
    colourtokens: 'Colour tokens',
    components: 'Components',
    componentsoverview: 'Components overview',
    mapcomponents: 'Map Components',
    mapcomponentsoverview: 'Map components overview',
    cssshortcuts: 'CSS shortcuts',
    cssshortcutsoverview: 'CSS shortcuts overview',
    spacingtokens: 'Spacing tokens',
    typographytokens: 'Typography tokens',
    designtokens: 'Design tokens',
    getinvolved: 'Get involved',
    starttouse: 'How to install',
    finddemo: 'Find a demo',
    pagetemplates: 'Page templates',
    pagetemplatesoverview: 'Page templates overview',
    stylesoverview: 'Styles overview',
  },
  fr: {
    label: 'Extension cartographique du Système de design GC',
    home: 'Extension cartographique du Système de design GC',
    contact: 'Contact',
    contactus: 'Nous contacter',
    colourtokens: 'Unités de style de couleur',
    components: 'Composants',
    componentsoverview: 'Aperçu des composants',
    mapcomponents: 'Composants de carte',
    mapcomponentsoverview: 'Aperçu des composants de carte',
    cssshortcuts: 'Raccourcis CSS',
    cssshortcutsoverview: 'Aperçu des raccourcis CSS',
    spacingtokens: "Unités de style d’espacement",
    typographytokens: 'Unités de style typographie',
    designtokens: 'Unités de style',
    getinvolved: 'S’impliquer',
    starttouse: 'Comment installer',
    finddemo: 'Trouver une démo',
    pagetemplates: 'Modèles de page',
    pagetemplatesoverview: 'Aperçu des modèles de page',
    stylesoverview: 'Aperçu des styles',
  },
};
